src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
	
	/**
	* @ORM\OneToMany(targetEntity="App\Entity\Plan_formation", mappedBy="formation")
	*/
	private $plans; // Ici plans prend un « s », car une formation a plusieurs plans !
	
    /**
     * @ORM\Column(type="string", length=50)
     */
    private $libelle;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $niveau;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type_form;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $diplomante;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="float")
     */
    private $coutrevient;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }
    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }
    public function setNiveau(string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getTypeForm(): ?string
    {
        return $this->type_form;
    }
    public function setTypeForm(string $type_form): self
    {
        $this->type_form = $type_form;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDiplomante(): ?bool
    {
        return $this->diplomante;
    }
    public function setDiplomante(bool $diplomante): self
    {
        $this->diplomante = $diplomante;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }
    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getCoutrevient(): ?float
    {
        return $this->coutrevient;
    }
    public function setCoutrevient(float $coutrevient): self
    {
        $this->coutrevient = $coutrevient;

        return $this;
    }
	
		/**
     *
     *
     * @return string
     */
    public function affichage()
    {
        return ($this->libelle . "-" . $this->niveau);
    }
	
	/**
     * Constructor
     */
    public function __construct()
    {
        // on a un attribut qui doit contenir un ArrayCollection, on doit l'initialiser dans le constructeur
		$this->plans = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add plan
     *
     * @param \App\Entity\Plan_formation $plan
     *
     * @return Formation
     */
    public function addPlan(\App\Entity\Plan_formation $plan)
    {
        $this->plans[] = $plan;
		$plans->setFormation($this);
        return $this;
    }
    /**
     * Remove plan
     *
     * @param \App\Entity\Plan_formation $plan
     */
    public function removePlan(\App\Entity\Plan_formation $plan)
    {
        $this->plans->removeElement($plan);
    }
    /**
     * Get plans
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPlans()
    {
        return $this->plans;
    }
}

src/Entity/Statut.php
<?php

namespace App\Entity;

use App\Repository\StatutRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StatutRepository::class)
 */
class Statut
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $type;
	
	/**
     * @ORM\Column(type="float")
     */
    private $taux_horaire;
	
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTauxHoraire(): ?float
    {
        return $this->taux_horaire;
    }

    public function setTauxHoraire(float $taux_horaire): self
    {
        $this->taux_horaire = $taux_horaire;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

// Nécessaire pour la pagination
use Symfony\Component\HttpFoundation\Request; // Nous avons besoin d'accéder à la requête pour obtenir le numéro de page
use Knp\Component\Pager\PaginatorInterface; // Nous appelons le bundle KNP Paginator

use App\Entity\Client;
use App\Entity\Statut;
use App\Entity\Formation;
use App\Entity\Session_formation;
use App\Entity\Plan_formation;

use App\Form\ClientType;
use App\Form\ClientCompletType;
use App\Form\StatutType;
use App\Form\FormationType;
use App\Form\SessionType;
use App\Form\PlanFormationType;

use App\Repository\ClientRepository;
use App\Repository\StatutRepository;
use App\Repository\FormationRepository;
use App\Repository\Session_formationRepository;
use App\Repository\Plan_formationRepository;

use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="login_administrateur")
	 *
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="deconnexion")
     */
    public function logout()
    {
        return new RedirectResponse($this->urlGenerator->generate('accueil'));
    }

    /**
     * @Route("/security/statut/liste", name="adminStatutListe")
	 *
	 * @Security("is_granted('ROLE_ADMIN')")
     */
	// Gestion des statuts
	public function listeStatut(Request $request, PaginatorInterface $paginator)
	{
		$manager = $this->getDoctrine()->getManager();
		$rep = $manager->getRepository(Statut::class);
		$lesStatuts = $rep->findAll();
		
		$lesStatutsPagines = $paginator->paginate(
            $lesStatuts, // Requête contenant les données à paginer (ici nos statuts)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            4 // Nombre de résultats par page
        );
				
		return $this->render('Admin/statut.html.twig', Array('lesStatuts' => $lesStatutsPagines));
    }
    /**
     * @Route("/security/statut/modif/{id}", name="adminStatutModif")
	 *
	 * @Security("is_granted('ROLE_ADMIN')")
     */
	// Affichage du formulaire de modification d'un statut
	public function modifStatut($id, Request $request, PaginatorInterface $paginator)
    {
        // Récupération du statut d'identifiant $id
		$em = $this->getDoctrine()->getManager();
		$rep = $em->getRepository(Statut::class);
		$statut = $rep->find($id);
		
		
		// Création du formulaire à partir du statut récupéré
		$form = $this->createForm(StatutType::class, $statut);
		
		// Mise à jour de la bdd si method POST ou affichage du formulaire dans le cas contraire
		if ($request->getMethod() == 'POST')
		{
			$form->handleRequest($request); // permet de récupérer les valeurs des champs dans les inputs du formulaire.
			if ($form->isValid())
			{
				// mise à jour de la bdd
				$em->persist($statut);
				$em->flush();
				//echo "URL:" . $this->getBaseUrl();

				// Réaffichage de la liste des statuts
				$lesStatuts = $rep->listeStatuts();
				$lesStatutsPagines = $paginator->paginate(
					$lesStatuts, // Requête contenant les données à paginer (ici nos statuts)
					$request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
					4 // Nombre de résultats par page
				);
				return $this->render('security/statut.html.twig', Array('lesStatuts' => $lesStatutsPagines));
			}
		}
		// Si formulaire pas encore soumis ou pas valide (affichage du formulaire)
		return $this->render('security/formStatut.html.twig', array('form' => $form->createView(), 'action' => 'modification'));
    }
    /**
     * @Route("/security/statut/supp/{id}", name="adminStatutSupp")
	 *
	 * @Security("is_granted('ROLE_ADMIN')")
     */
	public function suppStatut($id, Request $request, PaginatorInterface $paginator) // Affichage du formulaire de suppression d'un statut
    {
        // Récupération du statut d'identifiant $id
		$em = $this->getDoctrine()->getManager();
		$rep = $em->getRepository(Statut::class);
		$statut = $rep->find($id);
		
		// Création du formulaire à partir du statut récupéré
		$form = $this->createForm(StatutType::class, $statut);
		
		// Mise à jour de la bdd si method POST ou affichage du formulaire dans le cas contraire
		if ($request->getMethod() == 'POST')
		{
			$form->handleRequest($request); // permet de récupérer les valeurs des champs dans les inputs du formulaire.
			
			// mise à jour de la bdd
			$res = $rep->suppStatut($id);
			$em->persist($statut);
			$em->flush();
				
			// Réaffichage de la liste des statuts
			$lesStatuts = $rep->listeStatuts();
			$lesStatutsPagines = $paginator->paginate(
				$lesStatuts, // Requête contenant les données à paginer (ici nos statuts)
				$request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
				4 // Nombre de résultats par page
			);
			return $this->render('security/statut.html.twig', Array('lesStatuts' => $lesStatutsPagines));
		}
		// Si formulaire pas encore soumis ou pas valide (affichage du formulaire)
		return $this->render('security/formStatut.html.twig', array('form' => $form->createView(), 'action' => 'suppression'));
    }
	/**
     * @Route("/security/client/liste", name="adminClientListe")
	 * 
	 * @Security("is_granted('ROLE_ADMIN')")
     */
	// Gestion des clients
	public function listeClient(Request $request, PaginatorInterface $paginator)
	{
		$manager = $this->getDoctrine()->getManager();
		$rep = $manager->getRepository(Client::class);
		$lesClients = $rep->findAll();
		
		$lesClientsPagines = $paginator->paginate(
            $lesClients, // Requête contenant les données à paginer (ici nos clients)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            4 // Nombre de résultats par page
        );
				
		return $this->render('security/client.html.twig', Array('lesClients' => $lesClientsPagines));
	}
	/**
     * @Route("/security/client/modif/{id}", name="adminClientModif")
	 * 
	 * @Security("is_granted('ROLE_ADMIN')")
     */
	// Affichage du formulaire de modification d'un client
	public function modifClient($id, Request $request, PaginatorInterface $paginator) // Affichage du formulaire de modification d'un client
    {
        // Récupération du client d'identifiant $id
		$em = $this->getDoctrine()->getManager();
		$rep = $em->getRepository(Client::class);
		$client = $rep->find($id);
		
		
		// Création du formulaire à partir du client récupéré
		$form = $this->createForm(ClientCompletType::class, $client);
		
		// Mise à jour de la bdd si method POST ou affichage du formulaire dans le cas contraire
		if ($request->getMethod() == 'POST')
		{
			$form->handleRequest($request); // permet de récupérer les valeurs des champs dans les inputs du formulaire.
			if ($form->isValid())
			{
				// mise à jour de la bdd
				$em->persist($client);
				$em->flush();
				
				// Réaffichage de la liste des clients
				$lesClients = $rep->listeClients();
				$lesClientsPagines = $paginator->paginate(
					$lesClients, // Requête contenant les données à paginer (ici nos clients)
					$request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
					4 // Nombre de résultats par page
				);
				return $this->render('security/client.html.twig', Array('lesClients' => $lesClientsPagines));
			}
		}
		// Si formulaire pas encore soumis ou pas valide (affichage du formulaire)
		return $this->render('security/formClient.html.twig', array('form' => $form->createView(), 'action' => 'modification'));
	}
	/**
     * @Route("/security/client/supp/{id}", name="adminClientSupp")
	 * 
	 * @Security("is_granted('ROLE_ADMIN')")
     */
	public function suppClient($id, Request $request, PaginatorInterface $paginator) // Affichage du formulaire de suppression d'un client
    {
        // Récupération du client d'identifiant $id
		$em = $this->getDoctrine()->getManager();
		$rep = $em->getRepository(Client::class);
		$client = $rep->find($id);
		
		// Création du formulaire à partir du client récupéré
		$form = $this->createForm(ClientCompletType::class, $client);
		
		// Mise à jour de la bdd si method POST ou affichage du formulaire dans le cas contraire
		if ($request->getMethod() == 'POST')
		{
			$form->handleRequest($request); // permet de récupérer les valeurs des champs dans les inputs du formulaire.
			
			// mise à jour de la bdd
			$res = $rep->suppClient($id);
			$em->persist($client);
			$em->flush();
				
			// Réaffichage de la liste des clients
			$lesClients = $rep->listeClients();
			$lesClientsPagines = $paginator->paginate(
				$lesClients, // Requête contenant les données à paginer (ici nos clients)
				$request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
				4 // Nombre de résultats par page
			);
			return $this->render('security/client.html.twig', Array('lesClients' => $lesClientsPagines));
		}
		// Si formulaire pas encore soumis ou pas valide (affichage du formulaire)

templates/security/accueil.html.twig
{% extends 'layout.html.twig' %}
{% block FormArmor_body %}
	<h2>Gestion des données</h2>
{% endblock %}

templates/security/client.html.twig
{% extends 'layout.html.twig' %}
{% block FormArmor_body %}
	<h2>AFFICHAGE DES CLIENTS</h2>
	<table class="table">
		<thead>
		<tr>
			<th>Id</th>
			<th>Statut</th>
			<th>Nom</th>
			<th>Adresse</th>
			<th>Code postal</th>
			<th>Ville</th>
			<th>Compta</th>
			<th>Bureautique</th>
			<th colspan ="2">Option</th>
		</tr>
		</thead>
		<tbody>
			{% for client in lesClients %}
				<tr {# si le nombre de passages dans la boucle est pair #} {% if loop.index is even %} class="success" {% else %} class="info" {% endif %}>
					<td>{{client.id}}</td>
					<td>{{client.statut.type}}</td>
					<td>{{client.nom}}</td>
					<td>{{client.adresse}}</td>
					<td>{{client.cp}}</td>
					<td>{{client.ville}}</td>
					<td>{{client.nbhcpta}}</td>
					<td>{{client.nbhbur}}</td>
					<td><a href="{{ path('adminClientModif', {'id': client.id}) }}">Modifier</a></td>
					<td><a href="{{ path('adminClientSupp', {'id': client.id}) }}">Supprimer</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	
	{{ knp_pagination_render(lesClients) }}
	
	<script>
		$(function() {
			$('#menu2').attr('class', 'active');
		});
	</script>
	
{% endblock %}

templates/security/formClient.html.twig
{% extends 'layout.html.twig' %}
{% block FormArmor_body %}
	<h3>Formulaire de {{ action }} du client</h3>

	<div class="well">
	  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

	  {# Les erreurs générales du formulaire. #}
	  {{ form_errors(form) }}

	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.statut, "Statut : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.statut) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.statut, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du contrôle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.nom, "Nom : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.nom) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.adresse, "Adresse : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.adresse) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.cp, "Code postal : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.cp) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.cp, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.ville, "Ville : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.ville) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.email, "E Mail : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.email) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.nbhcpta, "Nombre d'heures compta : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.nbhcpta) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.nbhcpta, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.nbhbur, "Nombre d'heures bureautique : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.nbhbur) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.nbhbur, {'attr': {'class': 'form-control'}}) }}
	  <br/>
	  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
	  {{ form_widget(form.Valider, {'attr': {'class': 'btn btn-danger'}}) }}
	  
	  {# Bouton permettant de revenir à la page précédente sans valider #}
	  <input type="button" value="Retour" class = "btn btn-primary" onClick="history.go(-1)" />

	  {# Génération automatique des champs pas encore écrits.
		 Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
		 et tous les champs cachés (type hidden ). #}
	  {{ form_rest(form) }}

	  {# Fermeture de la balise <form> du formulaire HTML #}
	  {{ form_end(form) }}
	</div>
	<script>
		$(function() {
			$('#menu1').attr('class', 'active');
		});
	</script>
	
{% endblock %}

templates/security/formFormation.html.twig
{% extends 'layout.html.twig' %}
{% block FormArmor_body %}
	<h3>Formulaire de {{ action }} de la formation</h3>

	<div class="well">
	  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

	  {# Les erreurs générales du formulaire. #}
	  {{ form_errors(form) }}

	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.libelle, "Libell&eacute; : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.libelle) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.libelle, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.niveau, "Niveau : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.niveau) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.niveau, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.typeForm, "Type de formation : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.typeForm) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.typeForm, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.description, "Description : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.description) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.diplomante, "Diplomante : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.diplomante) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.diplomante, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.duree, "Duree : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.duree) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.duree, {'attr': {'class': 'form-control'}}) }}
	  {# Génération du controle de façon détaillée pour l'exemple #}
		  {# Génération du label. #}
		  {{ form_label(form.coutrevient, "Cout de revient : ", {'label_attr': {'class': 'form-label'}}) }}
		  {# Affichage des erreurs pour ce champ précis. #}
		  {{ form_errors(form.coutrevient) }}
		  {# Génération de l'input. #}
		  {{ form_widget(form.coutrevient, {'attr': {'class': 'form-control'}}) }}
	  <br/>
	  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
	  {{ form_widget(form.Valider, {'attr': {'class': 'btn btn-danger'}}) }}
	  
	  {# Bouton permettant de revenir à la page précédente sans valider #}
	  <input type="button" value="Retour" class = "btn btn-primary" onClick="history.go(-1)" />

	  {# Génération automatique des champs pas encore écrits.
		 Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
		 et tous les champs cachés (type hidden ). #}
	  {{ form_rest(form) }}

	  {# Fermeture de la balise <form> du formulaire HTML #}
	  {{ form_end(form) }}
	</div>
	<script>
		$(function() {
			$('#menu3').attr('class', 'active');
		});
	</script>
	
{% endblock %}

templates/security/formation.html.twig
{% extends 'layout.html.twig' %}
{% block FormArmor_body %}
	<h2>AFFICHAGE DES FORMATIONS</h2>
	<table class="table">
		<thead>
		<tr>
			<th>Id</th>
			<th>Libelle</th>
			<th>Niveau</th>
			<th>Type</th>
			<th>Diplomante</th>
			<th>Dur&eacute;e</th>
			<th>Cout de revient</th>
			<th colspan="2">Option</th>
		</tr>
		</thead>
		<tbody>
			{% for formation in lesFormations %}
				<tr {# si le nombre de passages dans la boucle est pair #} {% if loop.index is even %} class="success" {% else %} class="info" {% endif %}>
					<td>{{formation.id}}</td>
					<td>{{formation.libelle}}</td>
					<td>{{formation.niveau}}</td>
					<td>{{formation.typeForm}}</td>
					{% if (formation.diplomante == 1) %}
						<td>Oui</td>
					{% else %}
						<td>Non</td>
					{% endif %}
					<td>{{formation.duree}}</td>
					<td>{{formation.coutrevient}}</td>
					<td><a href="{{ path('adminFormationModif', {'id': formation.id}) }}">Modifier</a></td>
					<td><a href="{{ path('adminFormationSupp', {'id': formation.id}) }}">Supprimer</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	
	{{ knp_pagination_render(lesFormations) }}
	
	<script>
		$(function() {
			$('#menu3').attr('class', 'active');
		});
	</script>
	
{% endblock %}

templates/security/statut.html.twig
{% extends 'layout.html.twig' %}
{% block FormArmor_body %}
	<h2>AFFICHAGE DES STATUTS</h2>
	<table class="table">
		<thead>
		<tr>
			<th>Identifiant</th>
			<th>Type</th>
			<th>Taux Horaire</th>
			<th>Option</th>
		</tr>
		</thead>
		<tbody>
			{% for statut in lesStatuts %}
				<tr {# si le nombre de passages dans la boucle est pair #} {% if loop.index is even %} class="success" {% else %} class="info" {% endif %}>
					<td>{{statut.id}}</td>
					<td>{{statut.type}}</td>
					<td>{{statut.tauxHoraire}}</td>
					<td><a href="{{ path('adminStatutModif', {'id': statut.id}) }}">Modifier</a></td>
					<td><a href="{{ path('adminStatutSupp', {'id': statut.id}) }}">Supprimer</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	
	{{ knp_pagination_render(lesStatuts) }}
	
	<script>
		$(function() {
			$('#menu1').attr('class', 'active');
		});
	</script>
	
{% endblock %}